language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
after_success:
  - yarn build
  - cp .git dist/ -r # required by semantic release
  - cp README.md dist/
  - cd dist
  - yarn install
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
