sudo: false
language: node_js
node_js: stable

addons:
  firefox: "45.0"

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - npm prune

script:
- npm run lint
- npm run test

after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start